name: First Workflow
on: [push]
jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome
        run: echo "Hello World"
      - name: Check Node and NPM Version
        run: |
          node -v
          npm -v
