name: First Workflow
on: [push]
jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome
        run: echo "Hello World"
      - name: Check Node and NPM Version
        run: |
          node -v
          npm -v
  runner-on-mac:
    runs-on: macos-latest
    steps:
      - name: Check Version
        run: sw_vers
  test-dependency:
    runs-on: windows-latest
    needs: run-shell-commands
    steps:
      - name: Test Print
        run: Write-Output "Hello Boss"
      - name: Error Step
        run: doesnotexitsanymore
