name: Internal Message Prompt
on: [push]

jobs:
  runner-error-and-warning-message:
    runs-on: ubuntu-latest
    steps:
    - name: error message
      run: echo "::error title=InternaL Error,file=convert.js,line=5,endLine=10,columnn=2,endColumn=8::Missing semicolon."
    - name: warning message
      run: echo "::warning title=Beware,file=convert.js,line=7,endLine=10,columnn=2,endColumn=8::It's recommended to have text minimum of 25 characters."
  runner-notice-and-debug-message:
    runs-on: windows-latest
    steps:
    - name: notice message
      run: echo "::notice title=Attention Please,file=convert.js,line=3,endLine=7,column=2,endColumn=10::You're awesome."
    - name: debug message
      run: echo "::debug title=Debug-debug,file=convert.js,line=5,endLine=8,column=4,endColumn=8::This is the function to test or prompt variant of runner message."
  runner-group-of-logs:
    runs-on: macos-latest
    steps:
    - name: group of log
      run: |
        echo "::group::Group of Logs"
        echo "This is demo of log line 1"
        echo "This is demo of log line 2"
        echo "This is demo of log line 3"
        echo "This is demo of log line 4"
        echo "This is demo of log line 5"
        echo "::endgroup::"
  runner-secret:
    runs-on: ubuntu-latest
    steps:
    - name: ssSSttt this is secret
      run: echo "::add-mask::Password"
    - name: show password
      run: echo "This is my password = Password"